# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Yo2ExDXl6I2D9ouHRs22q79jImR/uPUyJ/TzDtN279V5YOdIG0ySh/roGbITNpZTqP4QcSR1k82ImDHzDjCYoAsbMKn2bEvcFrus/UIcoFhKf0snRt2ameimbV4cLPc6bFK4wd2dx+6KWva7G0GXdVK2I2aFCyF4bRoBOQmYYS2uA50F7zt6nEj+5WukcqC39I0lpE/VZU+eNk3OkmBcISwdTJGKCt6FG2OCof0tfVoJwqESe4GbTO2v1zujiDKAF4G0x/2+qKu6AxsUAkjSn+xKkcyYMjSTYsKbkyP+6mCtIGyMvn7QYk6DQ19nJUVNNanGVFPbjKqWnZC6oTxhhv/L7kKOTvagZrcKYvRYlPj7hJ/h89ddDjMLR5VWo/4/gsZbXRT5XA7WKa95amQXa5Ukje6yJoEevaYaTSBuLqPpvftTpxii0/UegVatxT8/kJ85etnGNTYBVOLnBj6M09EG242w1V/4rgBQgqimuPPGZ+DCD/+kC8aFgt/EoersYantwmIkAr45zMZlC3wo3ACIcPtDgSAg6HxX94PPousrUeA1F60+F3CaehP2mPUHOFHErP7RECYGU4/hG6vBzEAIBdhQditi4hpBNpJbEkpHbcz4BPejoTD3zJR+3bpTc+FlAiY3hSxEGHUS2WF7FKSgkKMGCZm1E+nFuF3/Hsg="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
