travis:
  secure:
    BINSTAR_TOKEN: Y38SuOjtTX4dyWKgHzCIIMijLgw2/EEbSeAtdsMktZJYHbM6NOSP5RxPPux2e8bPOsJ8ME0PYQt88giKSXO/JbOEXIu6LVv9AY/+eke1TxUdC0/fCwZZ1/UAZ7vLcleutChvSYNHAxxoqrPjY0JtsbJPgum8Lf6zPm9aDyu3FLJULDXP7c+XslTy9ngJHOPiye6DW6VLHMS+zo+2Z5mQFw+2MPv7EYPmFm4/FmkA2iib907YrPBeLV2dwbPhtogY32SsDOX8/FMwbGPHw8ugAhnYYvZlxEA/AVYM4iJSTfg5log7WJ3D/cKgYZLTYhkLdb8jj4d7hHoCVSP/4edk7RL35vbxKEYk5243JLcHZ3VwsUT6G5Olm3Rv0yFeYdAjYCV6O3utSnq3nhVAab4M5io5Mr7NxiM2VIZ5F6vw5vo56DUFiFcklqPCAgX4n2QJnnWXLIftXX7u12tJTYxSVACFfptNmpdPlbzXw8Spd3V8KTUJvFvndFqZEhZrN78P0zk8oqjvISF70xP2124PjEqEJBgo3Prw65oNxlv2rHkg3KS/EhfjuxycrbCmvkEYdi0Q+BEHVC8C+2DsspY0MQk0Z9T8gR9HPa2wXhFhmYCGgGj5QexWHM5szfeBBa3jPdE5nJMYtGgTVLUXD69YDDxHB9vyN+vZ7maEKPLnNLs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
